-- ENUM Types for Order Service
CREATE TYPE order_status_enum AS ENUM ('NEW', 'PROCESSING', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'AWAITING_PAYMENT', 'PAYMENT_FAILED', 'REFUNDED', 'ON_HOLD', 'PARTIALLY_SHIPPED', 'DELIVERED');
